[mouse]
    bindings = [
        { mouse = "Right", action = "Paste" },
    ]
[font]
# Global font size in points
size = 12.0

# Normal (regular) font
[font.normal]
family = "FiraMonoNerdFontMono"
style = "Medium"

# Bold font
[font.bold]
family = "FiraMonoNerdFontMono"
style = "Bold"
