#Swap Prefix to backtick `
unbind C-b
set-option -g prefix `
bind-key ` send-prefix

#Enable scrolling/Mouse Support/Right click to open menu
set -g mouse on

#Prettify
set -g status-style bg="#07555f",fg="#d7d7af"
set -g pane-border-style fg="#07555f"
set -g pane-active-border-style fg="#8beaf6"
set -g status-right "pre ` z-zoom x-exit #(hostname -i) #(cat /sys/class/power_supply/*/capacity | head -1)""%"
#Last #() is battery %
