font_size 12.0
cursor_blink_interval 0
font_family FiraMono Nerd Font Mono Medium
bold_font FiraMono Nerd Font Mono Bold
url_style straight
tab_bar_style powerline
tab_powerline_style slanted
notify_on_cmd_finish invisible
#-------------------------------------------------------------KEYBINDS
mouse_map right press grabbed,ungrabbed paste_from_clipboard

#kitty_mod+enter is new window
map kitty_mod+up next_window
map kitty_mod+down previous_window

map kitty_mod+' new_tab_with_cwd
#kitty_mod left and right cycles tabs
enabled_layouts tall,stack
#Kitty_mod+L toggles zoom on tab (actually just swapping layout)
#kitty_mod+f5 reloads kitty.conf
#kitty_mod is Ctrl+Shift


#Upgrading kitty to newest version will allow for drag and drop tabs(even dropping to make new OS window) and mouse resizing of windows
#Cursor trail needs an updated version as well
#cursor_trail 200
#cursor_trail_decay 0.1 0.4
#cursor_trail_start_threshold 2

# BEGIN_KITTY_THEME
# Tmrwcustom
include current-theme.conf
# END_KITTY_THEME
