font_size 12.0
cursor_blink_interval 0
font_family FiraMono Nerd Font Mono Medium
bold_font FiraMono Nerd Font Mono Bold
mouse_map right press grabbed,ungrabbed paste_from_clipboard
url_style straight

# BEGIN_KITTY_THEME
# Gruvbox Material Dark Hard
include current-theme.conf
# END_KITTY_THEME
